name: Test main lib
on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'tests/**'
    - '.github/workflows/test-main-lib.yml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'tests/**'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - '.github/workflows/test-main-lib.yml'

jobs:
  test-main-lib:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Test publish
      run: cargo publish --dry-run
      if: matrix.os == 'ubuntu-latest'

    - name: Test
      run: cargo test
