name: Test nlpo3-cli
on:
  push:
    branches:
      - main
    paths:
      - 'nlpo3-cli/**'
  pull_request:
    branches:
      - main
    paths:
      - 'nlpo3-cli/**'

defaults:
  run:
    working-directory: nlpo3-cli

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        bitness: [64]  # 32, 64
        include:
          - os: windows-latest
            bitness: 32

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain - non-win32
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
        if: ${{ !startsWith(matrix.os, 'windows') || matrix.bitness != '32' }}

      - name: Setup Rust toolchain - win32
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          target: i686-pc-windows-msvc
        if: startsWith(matrix.os, 'windows') && matrix.bitness == '32'

      - name: Setup Rust dependencies
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
