name: Test main lib
on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
    - 'Cargo.toml'
    - 'tests/**'
    - '.github/workflows/test-main-lib.yml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
    - 'tests/**'
    - 'Cargo.toml'
    - '.github/workflows/test-main-lib.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        bitness: [64]  # 32, 64
        include:
        - os: windows-latest
          bitness: 32

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Test
      run: |
        ls "$HOME/.cargo/bin"
        cargo test
